name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install linter
        run: npm install

      - name: Lint webpage
        run: |
          npx htmlhint *.html
          npx htmllint *.html
          npx markdownlint *.md
          npx stylelint *.css

      - name: Lint JavaScript
        run: |
          npx eslint *.js

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Npm install
        run: |
          npm install

      - name: Build webpage
        run: |
          npm run build --if-present

      - name: Test JavaScript
        run: |
          npm test

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: webpage-${{ github.sha }}
          path: |
            *.html
            *.css
            *.js
